@echo off
setlocal enabledelayedexpansion

echo ========================================
echo babyLLM Android Setup Script
echo ========================================
echo.

REM Navigate to android directory
cd /d "%~dp0android"

REM Check if Android SDK is set via ANDROID_HOME or ANDROID_SDK_ROOT
set SDK_PATH=
if defined ANDROID_HOME (
    set SDK_PATH=%ANDROID_HOME%
) else if defined ANDROID_SDK_ROOT (
    set SDK_PATH=%ANDROID_SDK_ROOT%
) else (
    REM Try common locations
    if exist "%LOCALAPPDATA%\Android\Sdk" (
        set SDK_PATH=%LOCALAPPDATA%\Android\Sdk
    ) else if exist "C:\Android\Sdk" (
        set SDK_PATH=C:\Android\Sdk
    )
)

if not defined SDK_PATH (
    echo WARNING: Android SDK not found!
    echo.
    echo Please set ANDROID_HOME environment variable or install Android SDK.
    echo Common locations:
    echo   - %%LOCALAPPDATA%%\Android\Sdk
    echo   - C:\Android\Sdk
    echo.
    echo You can also manually create local.properties with:
    echo   sdk.dir=C:\\Users\\YourUsername\\AppData\\Local\\Android\\Sdk
    echo.
    pause
    exit /b 1
)

echo Android SDK found at: %SDK_PATH%
echo.

REM Create local.properties
echo Creating local.properties...
(
    echo # Auto-generated by setup-android.bat
    echo # Location of the Android SDK
    echo sdk.dir=%SDK_PATH:\=\\%
) > local.properties

if exist "local.properties" (
    echo [SUCCESS] local.properties created successfully!
) else (
    echo [ERROR] Failed to create local.properties
    pause
    exit /b 1
)

echo.
echo ========================================
echo Setup Complete!
echo ========================================
echo.
echo Project is ready to build!
echo.
echo Next steps:
echo.
echo Option 1 - Android Studio:
echo   1. Open Android Studio
echo   2. File -^> Open -^> Select the 'android' folder
echo   3. Wait for Gradle sync to complete
echo   4. Click Run to build and install the app
echo.
echo Option 2 - Command Line:
echo   cd android
echo   gradlew.bat assembleDebug
echo   Output: app\build\outputs\apk\debug\app-debug.apk
echo.
echo Option 3 - Quick Build:
echo   Run: build-android.bat
echo.
pause
